package org.argus.feature_extractor

package object Libs {
  val harmfulLibs: List[String] = List(
    "com.google.android.info.SmsInfo",
    "com.google.android.service.UploadService",
    "com.uuservice.status.SysCaller.callSilentInstall",
    "com.uuservice.status.SilenceTool.MyThread.run",
    "com.android.XWLauncher.CustomShirtcutActivity",
    "com.android.XWLauncher.InstallShortcutReceiver",
    "com.android.Base.Tools.replace name",
    "com.android.JawbreakerSuper.Deamon",
    "com.umeng.adutils.AdsConnect",
    "com.umeng.adutils.SplashActivity",
    "com.android.sf.dna.Collection",
    "com.android.battery.a.pa",
    "com.android.providers.message.SMSObserver",
    "com.android.providers.message.Utils.sendSms",
    "com.android.MJSrceen.Activity.BigImageActivity",
    "com.android.service.MouaService.InitSms",
    "com.android.security.SecurityService.onStart",
    "com.android.smon.SecurityReceiver.sendSMS",
    "com.google.vending.CmdReceiver",
    "android.ad.appoffer.Copy_2_of_DownloadManager",
    "com.google.ssearch.SearchService",
    "com.google.update.UpdateService",
    "com.android.qiushui.app.dmc",
    "com.android.game.xiaoqiang.jokes.Data9",
    "com.googleapi.cover.Actor",
    "com.android.shine.MainActivity.proglayss_Click",
    "com.google.ads.analytics.Googleplay",
    "com.google.ads.analytics.ZipDecryptInputStream",
    "com.google.game.store.bean.MyConfig.getMsg",
    "com.google.dubest.eight.isAvilible",
    "com.android.MainService.SMSReceiver",
    "com.android.main.TANCActivity",
    "com.android.mmreader1030",
    "com.google.ads.AdRequest.isTestDevice",
    "com.adobe.flashplayer .FV.doInBackground",
    "com.adobe.flashplayer .FA.startService",
    "com.android.appupdate.UpdateService",
    "com.android.system.SurpriseService",
    "com.google.android.gmses.MyApp",
    "com.android.secphone.FileUtil.clearTxt"
  )

  val paymentLibs : List[String] = List(
    "com.google.android.gms:play-services-wallet",
    "com.adyen.checkout",
    "com.braintreepayments.api",
    "com.checkout.checkoutkit",
    "com.cybersource:inappsdk",
    "cloudpayments",
    "datatrans",
    "com.ebanx:sdk",
    "com.clover.sdk:clover-android-sdk",
    "com.heartlandpaymentsystems.globalpayments-sdk",
    "paysafe",
    "payture",
    "com.stripe:stripe-android",
    "worldpay",
    "paypal",
    "amazon",
    "skrill",
    "payu",
    "payza",
    "paytm",
    "paysimple",
    "epx",
    "bitpay",
    "bluesnap",
    "sagepay",
    "ebiz",
    "securionpay"
  )
}
